### ISSUE TITLE
Include resources.yml for new people. 

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode_pyback#29]
Instead of using static text files. The goal should be an interface in which a new resource is added and the form is generated based on the resource groups.

**Comment by wimo7083** [comment]
The file is pretty large. Will need to segment it based on type. Since users give us their interests upon joining, being able to see what current and new users are interested in is probably better than throwing a large file at them. I think that being able to get data from the Users Table: Column Interests is a good way of seeing what our users are interested in.

I'd like to be able to get the string data the users submit at registration and populate user resources based on that data.   We'll have to classify the `resources.yaml` items so that we can match up what users request with what we have.

**Comment by wimo7083** [comment]
Created sub-module director for handling this interface: 

[link](https://github.com/OperationCode/operation_code_pybot/tree/Route_decoration/ocbot/resources)

**Comment by hollomancer** [comment]
@aaron-suarez, how do you feel about breaking this into multiple yaml files?

**Comment by aaron-suarez** [comment]
@hollomancer, I think that's a great idea. That thought had crossed my mind as well. I think that breaking up the categories into their own files would be ideal. For example, about half of the file is Information Security resources, so that could definitely be its own file. 

I would like to collaborate with at least one other person to take a look at the categories and see how we can whittle them down. At that point, it will be more apparent exactly how this file should be broken up.

**Comment by hollomancer** [comment]
@wimo7083, if we start by just segmenting out information security resources into a separate .yaml file, does that make the sizing more reasonable to get started?

**Comment by aaron-suarez** [comment]
Per a DM on slack between @hollomancer and myself, we decided that since we want to put all this into a database instead of managing it via a text file, it would be better to just keep these in a single file until we can just load it into a SQL database of some sort. 

Does that mess up your plans @wimo7083? Let's talk about this further on slack and update this thread once we've come to a decision.

**Comment by wimo7083** [comment]
Removing this issue since we are working on a greenfield project for nothing but resources. 

https://github.com/OperationCode/resources_api
